export const RDV_LIST_REQUEST = 'RDV_LIST_REQUEST';
export const RDV_LIST_RECEIVED = 'RDV_LIST_RECEIVED';
export const RDV_LIST_ERROR = 'RDV_LIST_ERROR';
export const RDV_LIST_ADD = 'RDV_LIST_ADD';

export const RDV_REQUEST = 'RDV_REQUEST';
export const RDV_RECEIVED = 'RDV_RECEIVED';
export const RDV_ERROR = 'RDV_ERROR';
export const RDV_UNLOAD = 'RDV_UNLOAD';

export const MEDICAL_FORM_UNLOAD = 'MEDICAL_FORM_UNLOAD';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_CONFIRMATION_SUCCESS = 'USER_CONFIRMATION_SUCCESS';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const SYMPTOMES_ADD = 'SYMPTOMES_ADD';
export const TRAVEL_ADD = 'TRVEL_ADD';


export const PLACE_LIST_RECEIVED = 'PLACE_LIST_RECEIVED';
export const PLACE_LIST_ERROR = 'PLACE_LIST_ERROR';

export const IMAGE_UPLOADED = 'IMAGE_UPLOADED';
export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR';
export const IMAGE_DELETED = 'IMAGE_DELETED';
export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST';

export const APP_ADD = 'APP_ADD';