export const RDV_LIST_REQUEST = 'RDV_LIST_REQUEST';
export const RDV_LIST_RECEIVED = 'RDV_LIST_RECEIVED';
export const RDV_LIST_ERROR = 'RDV_LIST_ERROR';
export const RDV_LIST_ADD = 'RDV_LIST_ADD';

export const RDV_REQUEST = 'RDV_REQUEST';
export const RDV_RECEIVED = 'RDV_RECEIVED';
export const RDV_ERROR = 'RDV_ERROR';
export const RDV_UNLOAD = 'RDV_UNLOAD';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_CONFIRMATION_SUCCESS = 'USER_CONFIRMATION_SUCCESS';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';